#!/bin/sh

set -e

[ -f /etc/default/github-actions-test ] && . /etc/default/github-actions-test

startgithub-actions-test() {
  if [ -x /bin/systemctl ]; then
    /bin/systemctl daemon-reload
    /bin/systemctl restart github-actions-test
	elif [ -x "/etc/init.d/github-actions-test" ]; then
		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
			invoke-rc.d github-actions-test restart || true
		else
			/etc/init.d/github-actions-test restart || true
		fi
	fi
}

case "$1" in
	configure)
	[ -z "$github-actions-test_USER" ] && github-actions-test_USER="github-actions-test"
	[ -z "$github-actions-test_GROUP" ] && github-actions-test_GROUP="github-actions-test"
	if ! getent group "$github-actions-test_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$github-actions-test_GROUP" --quiet
	fi
	if ! id $github-actions-test_USER > /dev/null 2>&1 ; then
	    adduser --system --home /usr/share/github-actions-test --no-create-home \
		--ingroup "$github-actions-test_GROUP" --disabled-password --shell /bin/false \
		"$github-actions-test_USER"
	fi

  if [ -x /opt/github-actions-test/ ]; then
    echo "### Upgrading Notice ### "
    echo "-- New github-actions-test install home is /usr/share/github-actions-test"
    #echo "-- Please move sqlite3 database to /var/lib/github-actions-test/"
    echo "-- Notice: service name && binary changed to github-actions-test"
  fi

	# Set user permissions on /var/log/github-actions-test, /var/lib/github-actions-test
	mkdir -p /var/log/github-actions-test /var/lib/github-actions-test
	chown -R $github-actions-test_USER:$github-actions-test_GROUP /var/log/github-actions-test /var/lib/github-actions-test
	chmod 755 /var/log/github-actions-test /var/lib/github-actions-test

	# configuration files should not be modifiable by github-actions-test user, as this can be a security issue
	chown -Rh root:$github-actions-test_GROUP /etc/github-actions-test/*
	chmod 755 /etc/github-actions-test
	find /etc/github-actions-test -type f -exec chmod 640 {} ';'
	find /etc/github-actions-test -type d -exec chmod 755 {} ';'

	# if $2 is set, this is an upgrade
	if ( [ -n $2 ] && [ "$RESTART_ON_UPGRADE" = "true" ] ) ; then
		startgithub-actions-test
	# this is a fresh installation
	elif [ -z $2 ] ; then
        if [ -x /bin/systemctl ] ; then
            echo "### NOT starting on installation, please execute the following statements to configure github-actions-test to start automatically using systemd"
            echo " sudo /bin/systemctl daemon-reload"
            echo " sudo /bin/systemctl enable github-actions-test"
            echo "### You can start github-actions-test by executing"
            echo " sudo /bin/systemctl start github-actions-test"

        elif [ -x /usr/sbin/update-rc.d ] ; then
            echo "### NOT starting github-actions-test by default on bootup, please execute"
            echo " sudo update-rc.d github-actions-test defaults 95 10"
            echo "### In order to start github-actions-test, execute"
            echo " sudo service github-actions-test start"
        fi
	fi
	;;
esac
